quant_stage:
  quant_modifiers:
    QuantizationModifier:
      config_groups:
        group_0:
          targets: [Linear]
          weights:
            num_bits: 4
            type: int
            symmetric: true
            group_size: 128
            strategy: group
            block_structure: null
            dynamic: false
            actorder: static
            scale_dtype: null
            zp_dtype: null
            observer: minmax
            observer_kwargs: {}
          input_activations: null
          output_activations: null
          format: null
      targets: [Linear]
      ignore: [lm_head]
